"""Debug router — surfaces in-process profiling data to the Debug Panel.

Currently exposes the SQLite query ring buffer captured by
backend/utils/sqlite_profiler.py. No service-scoped auth: this is local-dev
observability that mirrors what the existing DuckDB Debug Panel already
surfaces from /api/query responses. Add auth here if this project ever
hardens for multi-tenant use.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query, Request

from backend.models.debug import ClearSqliteResponse, RecentSqliteResponse
from backend.models.errors import DEFAULT_ERROR_RESPONSES
from backend.utils import sqlite_profiler

router = APIRouter(prefix="/api/debug", tags=["debug"], responses=DEFAULT_ERROR_RESPONSES)


@router.get("/recent-sqlite", response_model=RecentSqliteResponse)
def recent_sqlite(
    request: Request,
    limit: int = Query(200, ge=1, le=1000),
    since_seq: int = Query(0, ge=0),
):
    """Return up to ``limit`` most-recent SQLite statements captured since
    ``since_seq``. The Debug Panel polls this every 2s when SQL debug is on.
    """
    is_remote = getattr(request.state, "is_remote", False)
    if is_remote:
        from backend.core.share_db.settings import get_setting

        q_vis = get_setting("query_debug_visibility", "disabled")
        if q_vis not in ("analysts", "both"):
            from backend.utils.router_utils import make_error

            raise HTTPException(
                status_code=403, detail=make_error("sql_debug_disabled", "SQL debug is disabled for analysts")
            )

    return sqlite_profiler.get_recent(limit=limit, since_seq=since_seq)


@router.post("/clear-sqlite", response_model=ClearSqliteResponse)
def clear_sqlite(request: Request):
    """Drain the SQLite ring buffer. Manual reset for the Debug Panel."""
    is_remote = getattr(request.state, "is_remote", False)
    if is_remote:
        from backend.utils.router_utils import make_error

        raise HTTPException(
            status_code=403, detail=make_error("admin_only", "Only administrators can clear the SQLite debug buffer")
        )

    sqlite_profiler.clear()
    return {"ok": True, **sqlite_profiler.buffer_stats()}


@router.get("/state")
def debug_state():
    """Report whether the backend will include ``_debug_queries`` /
    ``_debug_calls`` arrays in API responses.

    Controlled by the process-level ``DEBUG_RESPONSES`` env var (defaults
    OFF in production for security; ON in local-dev ``.env``). The admin
    page calls this to dim the "Query debugging panel" + "API call panel"
    toggles when the backend won't populate them — so the operator gets
    a clear tooltip explaining why their toggle has no effect, instead of
    silently flipping a switch that does nothing.
    """
    from backend.models.common import _debug_responses_enabled

    return {"debug_responses_enabled": _debug_responses_enabled()}


@router.get("/page-telemetry")
def get_page_telemetry_endpoint(
    page_load_id: str = Query(..., description="Unique page-load ID generated by the frontend"),
):
    """Retrieve all unified SQLite queries, DuckDB queries, FOS calls, and section timings
    matching the page_load_id.
    """
    from backend import config as svcconfig
    from backend.core.metadata import usage_log

    sid = svcconfig.get_active_service_id()
    if not sid:
        return {"queries": [], "sections": [], "calls": []}

    return usage_log.get_page_telemetry(sid, page_load_id)
