from datetime import UTC, datetime

from scripts.load_test.generate_synthetic_raw_logs import _synthetic_line


def test_synthetic_line_populates_dashboard_dimensions() -> None:
    line = _synthetic_line(datetime(2026, 9, 10, tzinfo=UTC), "test-service")

    expected_fields = {
        "timestamp",
        "ip",
        "host",
        "url",
        "method",
        "proto",
        "ua",
        "referer",
        "status",
        "country",
        "city",
        "region",
        "cache",
        "ttl",
        "age",
        "hits",
        "digest",
        "backend",
        "edge",
        "pop",
        "server_region",
        "tls",
        "is_ipv6",
        "conn_requests",
        "lat",
        "lon",
        "metro",
        "asn",
        "tcp_rtt",
        "transport",
        "ploss",
        "rtt_min",
        "rtt_var",
        "retrans",
        "bw",
        "elapsed",
        "ttfb",
        "req_bytes",
        "req_header_bytes",
        "resp_bytes",
        "resp_header_content_encoding",
        "p_type",
        "p_desc",
        "c_speed",
        "c_type",
        "delivery_rate",
        "data_segs_out",
        "ja3",
        "ja4",
        "tls_ciphers_sha",
        "cookie_session",
        "waf",
        "waf_resp",
        "waf_ms",
        "waf_sig",
        "waf_req_id",
        "q_rtt",
        "q_rtt_var",
        "q_lost",
        "q_cwnd",
        "ottfb",
        "ottlb",
        "oconnect_ms",
        "ost",
        "obytes",
        "oip",
        "oretries",
        "rid",
        "prid",
        "io_input_bytes",
        "io_output_bytes",
        "io_input_format",
        "io_output_format",
    }

    assert expected_fields <= line.keys()
    assert all(line[field] not in ("", None) for field in expected_fields)
