import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryClient, dehydrate } from "@tanstack/react-query";
import type { DehydratedState } from "@tanstack/react-query";
import "./globals.css";
import QueryProvider from "@/components/QueryProvider";
import ThemeProvider from "@/components/ThemeProvider";
import { AppLayout } from "@/components/AppLayout";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { getPreloadChunks } from "@/lib/preload-manifest";
import { fetchBootstrapServerSide } from "@/lib/ssr/bootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fastly Log Analytics",
  description: "Modern log analytics for Fastly Object Storage",
};

// O6 follow-up (2026-06-06): force-dynamic was previously set here so
// the preload-manifest could be read at request time (manifest is
// generated by ``scripts/build-preload-manifest.mjs`` AFTER ``next
// build``, so SSG-time reads return empty). The cost was an SSR
// roundtrip on EVERY page navigation — the "click does nothing for
// 100-300 ms" lag.
//
// The trade-off was bad: modulepreload saves ~200 ms ONE TIME on
// first dashboard/network page load, but force-dynamic was costing
// 100-300 ms PER navigation. Net loss across a session.
//
// Fix: removed ``force-dynamic`` here, made ``getPreloadChunks()``
// synchronous (module-load ``readFileSync``). Layout is back to a
// statically-renderable sync server component. Page navigations are
// instant again. The cost is that SSG-time reads return [] (manifest
// not written yet), so the static HTML has no ``<link rel="modulepreload">``
// tags. Browser falls back to discovering plotly via the normal
// main-bundle parse → dynamic-import → fetch path.
//
// A future optimization (bootstrap pattern: commit the manifest so a
// previous build's chunk names are baked into SSG of the next build)
// could restore the preload benefit without re-introducing the
// navigation lag.

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Modulepreload links from the build-time manifest (returns [] at
  // SSG-time since the manifest is generated AFTER next build).
  const preloadChunks = getPreloadChunks();

  // Per-request SSR fetch of /api/bootstrap. Pre-seeds React Query so
  // useBootstrap (and every dependent hook that reads bootstrap.* via
  // queryClient.getQueryData) finds data already cached on first
  // render — the cold-load /api/bootstrap RTT (300-600ms on prod
  // tunnel) drops off the client wait stack entirely, and the share
  // banner renders in the initial HTML paint instead of after a beat.
  //
  // fetchBootstrapServerSide returns null on any failure (network
  // blip, 5xx, timeout, missing API_PROXY_URL in pure `next dev`).
  // In that case we render the same tree as before and the client
  // useBootstrap falls back to its own fetch — never a broken page.
  const bootstrap = await fetchBootstrapServerSide();
  let dehydratedState: DehydratedState | null = null;
  if (bootstrap) {
    const client = new QueryClient();
    client.setQueryData(["bootstrap"], bootstrap);
    // Mirror the dependent seeds from useBootstrap.queryFn so hooks
    // that gate on bootstrap-pending find their slice in cache too.
    // Source of truth for the key shapes:
    // frontend/hooks/useBootstrap.ts:21-41.
    const sid = (bootstrap as { active_service_id?: string | null })?.active_service_id;
    if (sid) {
      const b = bootstrap as Record<string, unknown>;
      if (Array.isArray(b.views)) {
        client.setQueryData(["views", sid], b.views);
      }
      if (b.log_fields_catalog) {
        client.setQueryData(["log-fields-catalog", sid], b.log_fields_catalog);
      }
      if (b.sync_status) {
        client.setQueryData(["sync-status", sid], b.sync_status);
      }
      if (b.log_extents) {
        client.setQueryData(["log-extents", sid], b.log_extents);
      }
    }
    dehydratedState = dehydrate(client);
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {preloadChunks.map((href) => (
          <link key={href} rel="modulepreload" href={href} />
        ))}
        {/* world.geojson preload moved into <AppLayout> so it only emits
            on map-using routes (/dashboard, /network). Previously this
            was a global <link rel="preload">, which fired on every page
            including /share-login — wasting ~251KB of bandwidth for the
            unauthenticated share-login flow. */}
      </head>
      <body className={`${inter.className} antialiased`} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider dehydratedState={dehydratedState}>
            <TooltipProvider delay={0} closeDelay={0}>
              <AppLayout>
                <ErrorBoundary>{children}</ErrorBoundary>
              </AppLayout>
            </TooltipProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
