import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/QueryProvider";
import ThemeProvider from "@/components/ThemeProvider";
import { AppLayout } from "@/components/AppLayout";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { getPreloadChunks } from "@/lib/preload-manifest";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fastly Log Analytics",
  description: "Modern log analytics for Fastly Object Storage",
};

// O6 follow-up (2026-06-06): force-dynamic was previously set here so
// the preload-manifest could be read at request time (manifest is
// generated by ``scripts/build-preload-manifest.mjs`` AFTER ``next
// build``, so SSG-time reads return empty). The cost was an SSR
// roundtrip on EVERY page navigation — the "click does nothing for
// 100-300 ms" lag.
//
// The trade-off was bad: modulepreload saves ~200 ms ONE TIME on
// first dashboard/network page load, but force-dynamic was costing
// 100-300 ms PER navigation. Net loss across a session.
//
// Fix: removed ``force-dynamic`` here, made ``getPreloadChunks()``
// synchronous (module-load ``readFileSync``). Layout is back to a
// statically-renderable sync server component. Page navigations are
// instant again. The cost is that SSG-time reads return [] (manifest
// not written yet), so the static HTML has no ``<link rel="modulepreload">``
// tags. Browser falls back to discovering plotly via the normal
// main-bundle parse → dynamic-import → fetch path.
//
// A future optimization (bootstrap pattern: commit the manifest so a
// previous build's chunk names are baked into SSG of the next build)
// could restore the preload benefit without re-introducing the
// navigation lag.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Modulepreload links from the build-time manifest (returns [] at
  // SSG-time since the manifest is generated AFTER next build).
  const preloadChunks = getPreloadChunks();
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {preloadChunks.map((href) => (
          <link key={href} rel="modulepreload" href={href} />
        ))}
        {/* world.geojson preload moved into <AppLayout> so it only emits
            on map-using routes (/dashboard, /network). Previously this
            was a global <link rel="preload">, which fired on every page
            including /share-login — wasting ~251KB of bandwidth for the
            unauthenticated share-login flow. */}
      </head>
      <body className={`${inter.className} antialiased`} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <TooltipProvider delay={0} closeDelay={0}>
              <AppLayout>
                <ErrorBoundary>{children}</ErrorBoundary>
              </AppLayout>
            </TooltipProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
