apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastly-log-analytics.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "fastly-log-analytics.name" . }}-backend
    helm.sh/chart: {{ include "fastly-log-analytics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "fastly-log-analytics.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastly-log-analytics.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "fastly-log-analytics.name" . }}-frontend
    helm.sh/chart: {{ include "fastly-log-analytics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "fastly-log-analytics.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
