{{- if and .Values.secret.create (not .Values.secret.existingName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "high-scale.fullname" . }}-connections
  labels:
    {{- include "high-scale.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
