{{- include "clickhouse.validate" . -}}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.secretName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLICKHOUSE_USER: {{ .Values.auth.username | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.auth.password | quote }}
  CLICKHOUSE_DB: {{ .Values.auth.database | quote }}
{{- end }}
