/**
 * Verifies that dashboard filter URLs generated by security/network/origin pages
 * use the correct filter_ prefix format that useViewMetricUrlSync expects.
 *
 * These are static assertions against the URL format — they catch regressions
 * if someone renames a param prefix without updating useViewMetricUrlSync.
 */
import { describe, it, expect } from 'vitest'

/** Parse filter column names out of a dashboard URL query string. */
function filterKeysFrom(url: string): string[] {
  const qs = url.includes('?') ? url.split('?')[1] : url
  return Array.from(new URLSearchParams(qs).keys()).filter(k => k.startsWith('filter_'))
}

/** Assert all filter keys in a URL follow the filter_<col> convention. */
function assertFilterFormat(url: string) {
  const search = url.includes('?') ? url.split('?')[1] : url
  const params = new URLSearchParams(search)
  for (const key of params.keys()) {
    if (key.startsWith('filter')) {
      expect(key).toMatch(/^filter_\w+/)
    }
  }
}

describe('Security page dashboard links', () => {
  it('bot id filter uses filter_ prefix', () => {
    const url = `/dashboard?filter__wellknown_bot_id=${encodeURIComponent('bot-123')}`
    // Double underscore is intentional: column name is _wellknown_bot_id
    const keys = filterKeysFrom(url)
    expect(keys).toContain('filter__wellknown_bot_id')
  })

  it('ngwaf bot filter uses filter_ prefix', () => {
    const url = `/dashboard?filter__ngwaf_bot_name=${encodeURIComponent('scraperbot')}`
    const keys = filterKeysFrom(url)
    expect(keys).toContain('filter__ngwaf_bot_name')
  })

  it('tls fingerprint filter uses filter_ prefix', () => {
    const url = `/dashboard?filter_tls_client_hello=${encodeURIComponent('abc123')}`
    assertFilterFormat(url)
    expect(filterKeysFrom(url)).toContain('filter_tls_client_hello')
  })

  it('client IP filter uses filter_ prefix', () => {
    const url = `/dashboard?filter_client_ip=${encodeURIComponent('1.2.3.4')}`
    assertFilterFormat(url)
    expect(filterKeysFrom(url)).toContain('filter_client_ip')
  })
})

describe('Network page dashboard links', () => {
  it('POP filter uses filter_pop', () => {
    const pop = 'JFK'
    const url = `/dashboard?filter_pop=${encodeURIComponent(pop)}`
    assertFilterFormat(url)
    expect(new URLSearchParams(url.split('?')[1]).get('filter_pop')).toBe(pop)
  })

  it('shield POP filter uses filter_shield_pop', () => {
    const url = `/dashboard?filter_shield_pop=${encodeURIComponent('IAD')}`
    assertFilterFormat(url)
    expect(filterKeysFrom(url)).toContain('filter_shield_pop')
  })

  it('ASN filter uses filter_asn', () => {
    const url = `/dashboard?filter_asn=${encodeURIComponent('7922')}`
    assertFilterFormat(url)
    expect(filterKeysFrom(url)).toContain('filter_asn')
  })

  it('city/region/country multi-filter all use filter_ prefix', () => {
    const city = 'London'
    const region = 'ENG'
    const country = 'GB'
    const url = `/dashboard?filter_city=${encodeURIComponent(city)}&filter_region=${encodeURIComponent(region)}&filter_country=${encodeURIComponent(country)}`
    assertFilterFormat(url)
    const params = new URLSearchParams(url.split('?')[1])
    expect(params.get('filter_city')).toBe(city)
    expect(params.get('filter_region')).toBe(region)
    expect(params.get('filter_country')).toBe(country)
    // Must use prefixed parameter names (filter_city, not city)
    expect(params.has('city')).toBe(false)
    expect(params.has('region')).toBe(false)
  })
})

describe('Origin page dashboard links', () => {
  it('URL filter uses filter_url', () => {
    const url = `/dashboard?filter_url=${encodeURIComponent('/api/data')}`
    assertFilterFormat(url)
    expect(filterKeysFrom(url)).toContain('filter_url')
  })

  it('POP filter uses filter_pop', () => {
    const url = `/dashboard?filter_pop=${encodeURIComponent('SYD')}`
    assertFilterFormat(url)
    expect(filterKeysFrom(url)).toContain('filter_pop')
  })

  it('origin IP filter uses filter_oip (the actual schema column)', () => {
    // Backend filters on the real column name "oip"; the prior filter_origin_ip
    // pattern silently produced no rows because the table has no origin_ip column.
    const url = `/dashboard?filter_oip=${encodeURIComponent('10.0.0.1')}`
    assertFilterFormat(url)
    expect(filterKeysFrom(url)).toContain('filter_oip')
  })
})

describe('filter_ format is parseable by useViewMetricUrlSync', () => {
  it('all filter keys start with filter_ and are followed by at least one word char', () => {
    const sampleUrls = [
      `/dashboard?filter_status=200`,
      `/dashboard?filter_country=US&filter_pop=JFK`,
      `/dashboard?filter__wellknown_bot_id=bot-1`,
      `/dashboard?filter_city=London&filter_region=ENG&filter_country=GB`,
    ]
    for (const url of sampleUrls) {
      const params = new URLSearchParams(url.split('?')[1])
      for (const key of params.keys()) {
        // useViewMetricUrlSync does: key.startsWith('filter_') → col = key.substring(7)
        expect(key.startsWith('filter_')).toBe(true)
        const col = key.substring(7)
        expect(col.length).toBeGreaterThan(0)
      }
    }
  })
})
